# Generated by Django 5.0.4 on 2024-05-01 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('des_profile', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('des_subscription', models.CharField(max_length=100)),
                ('pri_subscription', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nam_user', models.CharField(max_length=300)),
                ('ema_user', models.CharField(max_length=300)),
                ('pass_user', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('id_subscription_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subscription')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
