# Generated by Django 5.0.4 on 2024-05-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='pri_subscription',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
