# Generated by Django 5.0.4 on 2024-05-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subscription_pri_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pass_user',
            new_name='pas_user',
        ),
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
