# Generated by Django 5.0.4 on 2024-05-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_pass_user_user_pas_user_user_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='des_subscription',
            field=models.CharField(max_length=90),
        ),
    ]
