# Generated by Django 5.0.4 on 2024-05-19 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_pas_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_profile_user',
            field=models.ForeignKey(default='5eab56af-60f5-4290-af60-a0dda32ee1af', on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_subscription_user',
            field=models.ForeignKey(default='b6f69838-82c8-454e-9937-9ab61d235400', on_delete=django.db.models.deletion.CASCADE, to='users.subscription'),
        ),
    ]
