# Generated by Django 5.0.4 on 2024-06-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_id_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ema_user',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
