# Generated by Django 5.0.4 on 2024-07-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_ema_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img_url',
            field=models.CharField(default='https://w7.pngwing.com/pngs/81/570/png-transparent-profile-logo-computer-icons-user-user-blue-heroes-logo.png'),
        ),
    ]
