# Generated by Django 5.0.4 on 2024-05-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='abb_language',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
