# Generated by Django 5.0.4 on 2024-05-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_language_abb_language'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpreferencetopic',
            unique_together={('id_user_preference', 'id_topic')},
        ),
    ]
